- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/AnnoObject.cs
- AnnoDesigner/Presets/BuildingInfo.cs
- AnnoDesigner/SerializableColor.cs
I added some attributes to have a better experience when debugging.
As I was exploring the code, I also made an adjustment to memory management. Since this method is called very rapidly, it is better to use a StringBuilder.
Maybe it would be better to call this method not that often.
Also added a postbuild to copy icons to the output directory. This is a much better experince for new developers. Open solution, compile and "It just works".
> better debug experience and some memory optimizations

- AnnoDesigner/MainWindow.xaml.cs
When Registry key's are not existing anymore do nothing, when they are remove the registry key's
> Fixed error message of the Unregister File Extensions

- PresetParser/ExtraPreset.cs
- PresetParser/ExtraPresets.cs
- PresetParser/PresetParser.csproj
- PresetParser/Program.cs
I think this is a little bit more maintainable.
> made logic for adding presets a bit more maintainable

- AnnoDesigner/AnnoObject.cs
- AnnoDesigner/DataIO.cs
- AnnoDesigner/Presets/BuildingInfo.cs
- AnnoDesigner/SerializableColor.cs
This just makes it nicer to look at the raw files.
> use fixed serialization order of properties

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/Presets/IconNameMap.cs
- AnnoDesigner/UI/IconImage.xaml.cs
I had the issue that there was no icon selected for the potato farm (Anno 1800).
The issue was a mismatch in the name.
presets.json: "A7_potatoes.png"
icon file: A7_Potatoes.png
> fix for not finding some icons

- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/App.xaml.cs
- AnnoDesigner/MainWindow.xaml
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/Properties/Settings.Designer.cs
- AnnoDesigner/Properties/Settings.settings
- AnnoDesigner/StringExtensions.cs
- AnnoDesigner/TreeViewExtensions.cs
- AnnoDesigner/TreeViewSearch.cs
- AnnoDesigner/app.config
Code to search the tree view. The search logic is abstracted away from the search box, so the input method can be changed or tweaked as required.
Should fix #31.
> Searchable treeview

- AnnoDesigner/Localization.cs
- AnnoDesigner/MainWindow.xaml.cs
Fixes a bug where clipboard text would not update when the language was changed.
> Localize clipboard

- AnnoDesigner/AnnoCanvas.xaml.cs
* Copy/Paste now requires the control key to be pressed to use.
* IsControlPressed actually looked at the Shift and Control keys, I have changed this so that it only looks at the Control key, and have added another function, IsShiftPressed().
> require copy/paste to use control key, add IsShiftPressed()

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/Localization.cs
- AnnoDesigner/MainWindow.xaml
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/model/Notify.cs
- AnnoDesigner/model/RelayCommand.cs
- AnnoDesigner/viewmodel/BuildingSettingsViewModel.cs
This should fix issue #55.
It is a first draft and not complete, but this is how I would tackle that issue.
A SplitButton hides some functions and doesn't add to much clutter to the UI.
What is missing:
- some text (ToolTips also)
- replacement for menu in dropdown
- placeholder logic for predefined colors
> change color of placed object(s)

- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/App.xaml.cs
- AnnoDesigner/ConnectivityHelper.cs
- AnnoDesigner/FileHelper.cs
- AnnoDesigner/Localization.cs
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/UpdateHelper.cs
I added some extra checks when auto updating the presets and fixed a potentional bug when extracting zip files.
- file attributes are set to normal before update/delete
- check if application can connect to the internet
> better resilience when auto updating presets

- AnnoDesigner/Presets/BuildingPresets.cs
"2205 modules appearing in 2070 section of the menu" should be fixed with this
> Fix-Issue-#80

- AnnoDesigner/MainWindow.xaml.cs
fix for #87 
remove ConfigureAwait(false) (context required)
> fix for #87

- AnnoDesigner/AnnoCanvas.xaml.cs
> fix for statistics not updated

- PresetParser/NewFactionAndGroup1800.cs
- Tests/PresetParser.Tests/NewFactionAndGroup1800Tests.cs
Just a couple more unit tests.
> more unit tests (NewFactionAndGroup1800)

- FandomTemplateExporter/FandomTemplateExporter/Export/FandomExporter.cs
This PR fixes an issue finding the correct `WikiBuildingInfo` by trying to find it for the correct region.
> fix for TemplateExporter

- FandomParser/InfoboxParser/InfoboxParser.cs
- FandomParser/InfoboxParser/Parser.cs
- FandomParser/Tests/InfoboxParser.Tests/Attributes/UseCultureAttribute.cs
- FandomParser/Tests/InfoboxParser.Tests/InfoboxParser.Tests.csproj
- FandomParser/Tests/InfoboxParser.Tests/InfoboxParserTests.cs
- FandomParser/Tests/InfoboxParser.Tests/ParserBothWorldsTests.cs
- FandomParser/Tests/InfoboxParser.Tests/ParserTests.cs
- FandomParser/Tests/InfoboxParser.Tests/SpecialBuildingNameHelperTests.cs
- PresetParser/Anno1404_Anno2070/IconNameMapper.cs
- PresetParser/Anno1404_Anno2070/LocalizationHelper.cs
- PresetParser/Anno1404_Anno2070/Models/GuidRef.cs
- PresetParser/Anno1800/Models/FarmField.cs
- PresetParser/Anno1800/NewFactionAndGroup1800.cs
- PresetParser/ExtraPresets.cs
- PresetParser/Models/ExtraPreset.cs
- PresetParser/Models/PathRef.cs
- PresetParser/PresetParser.csproj
- PresetParser/Program.cs
- PresetParser/Properties/AssemblyInfo.cs
- Tests/PresetParser.Tests/LocalizationHelperTests.cs
- Tests/PresetParser.Tests/NewFactionAndGroup1800Tests.cs
- Tests/PresetParser.Tests/PresetParser.Tests.csproj
This PR adds more unit tests and changes some code in `PresetParser`.
I did run the `PresetParser` for Anno 1404 before and after my changes and found no differences in the output.
> Add more unit tests

- PresetParser/Program.cs
- Tests/PresetParser.Tests/LocalizationHelperTests.cs
This PR adds more tests for the PresetsParser.
Also some code was refactored to be more maintainable.
> add more tests for PresetsParser

- FandomParser/FandomParser/Program.cs
- Presets/wikiBuildingInfo.json
This PR updates the presets file using the fixes from FandomParser.
> update wikiBuildingInfo presets file to version 2.1.0.0

- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/App.xaml.cs
This PR resets the settings if they become corrupt e.g. by an app crash.
> reset settings if corrupt

- FandomTemplateExporter/FandomTemplateExporter/Export/FandomExporter.cs
- FandomTemplateExporter/FandomTemplateExporter/Models/RelayCommand.cs
- FandomTemplateExporter/FandomTemplateExporter/ViewModels/MainWindowViewModel.cs
This PR fixes a miscalculation of produced products in a layout.
There are still some issues left, but it is significantly better than before.
Also the whole logic is async now.
> FandomTemplateExporter: fix calculation of produced products

- doc/Release_Workflow.md
This PR adds a document where a proposed (previously discussed) workflow for creating a new release is documented 🤓.
> add document for release workflow

- FandomTemplateExporter/FandomTemplateExporter/App.config
- FandomTemplateExporter/FandomTemplateExporter/App.xaml.cs
- FandomTemplateExporter/FandomTemplateExporter/Export/FandomExporter.cs
- FandomTemplateExporter/FandomTemplateExporter/FandomTemplateExporter.csproj
- FandomTemplateExporter/FandomTemplateExporter/MainWindow.xaml
- FandomTemplateExporter/FandomTemplateExporter/ViewModels/MainWindowViewModel.cs
This PR adds NLog and also the capability to copy the genrated template to the clipboard.
> add NLog to TemplateExporter

- ColorPresetsDesigner/App.config
- ColorPresetsDesigner/App.xaml.cs
- ColorPresetsDesigner/ColorPresetsDesigner.csproj
- ColorPresetsDesigner/MainWindow.xaml
- ColorPresetsDesigner/ViewModels/MainWindowViewModel.cs
This PR adds NLog to the ColorPresetsDesigner.
Also more issues when loading data are caught.
_hint: squash and merge_
> add NLog to ColorPresetsDesigner

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/Helper/CoordinateHelper.cs
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/model/ICoordinateHelper.cs
- Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
- Tests/AnnoDesigner.Tests/CoordinateHelperTests.cs
This PR extracts the CoordinateHelper and also adds some tests.
> extract CoordinateHelper

- AnnoDesigner/AnnoCanvas.xaml.cs
When Move Function is used, and try to Rotate a Single object, Clearing Function was not working well, this will Fix that issue #135
> Fix Clear Function #135

- AnnoDesigner.Core/Properties/AssemblyInfo.cs
- AnnoDesigner/Constants.cs
- AnnoDesigner/Properties/AssemblyInfo.cs
- PresetParser/Properties/AssemblyInfo.cs
This PR adjusts the version numbers.
To trigger the automatic in-app update, the `version.txt` needs to be adjusted.
> Preparation of release 8.4

- AnnoDesigner/viewmodel/MainViewModel.cs
This PR fixes the wrong image width on export.
> fix wrong width on export image

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/model/LayoutObject.cs
This PR reduces some calculations and optimizes the `OnRender` by a couple of ms.
Also there are less dictionary lookups which also contributes to a better performance.
> optimize performance a tiny bit

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/BrushCache.cs
- AnnoDesigner/PenCache.cs
- AnnoDesigner/model/IPenCache.cs
- AnnoDesigner/model/LayoutObject.cs
- AnnoDesigner/viewmodel/MainViewModel.cs
This PR adds a cache for  `Pen`s similar to the one for  `SolidColorBrush`es.
It improves performance/memory of layouts with many borderless objects.
> improve performance (cache Pens)

- AnnoDesigner/Localization/TreeLocalization.cs
-Update for Tree Localizations new Ornament Menu
> PreUpdate TreeLocalizations

- doc/Release_Workflow.md
This PR adds some information to the doc on what to do if you want to create a new release.
> add doc "How to create a new release"

- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/Helper/RoadSearchHelper.cs
- Tests/AnnoDesigner.Tests/RoadSearchHelperTests.cs
This PR fixes issue #197 and adds some tests to prevent the error in the future.
> fix issue #197

- AnnoDesigner/About.xaml
- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/App.xaml.cs
- AnnoDesigner/Localization/Localization.cs
- AnnoDesigner/Localization/LocalizeBinding.cs
- AnnoDesigner/Localization/TranslateExtension.cs
- AnnoDesigner/MainWindow.xaml
- AnnoDesigner/StatisticsView.xaml
- AnnoDesigner/UpdateHelper.cs
- AnnoDesigner/ViewModels/AboutViewModel.cs
- AnnoDesigner/ViewModels/BuildingSettingsViewModel.cs
- AnnoDesigner/ViewModels/MainViewModel.cs
- AnnoDesigner/ViewModels/PresetsTreeSearchViewModel.cs
- AnnoDesigner/ViewModels/StatisticsViewModel.cs
- Tests/AnnoDesigner.Tests/AboutViewModelTests.cs
- Tests/AnnoDesigner.Tests/BuildingSettingsViewModelTests.cs
- Tests/AnnoDesigner.Tests/MainViewModelTests.cs
So there don't have to be 100 properties in ViewModels just for translation texts
> Localization data binding

- AnnoDesigner/InputWindow.xaml
This PR fixes the missing translation in the input window (issue #207).
> fix issue #207

- AnnoDesigner/MainWindow.xaml
> Add Localize to StatusBarControls

- AnnoDesigner.Core/Presets/Loader/BuildingPresetsLoader.cs
- AnnoDesigner/MainWindow.xaml.cs
- AnnoDesigner/UpdateHelper.cs
This PR fixes #228.
Also some log entries have beeen added and adjusted.
> Properly support prereleases (fixes #228)

- AnnoDesigner/Localization/Localization.cs
Fixes a small typo in the "Hide influence on selection" option.
> Fix typo in General settings page

- AnnoDesigner/ViewModels/UpdateSettingsViewModel.cs
This PR makes use of `IMessageBoxService` in `UpdateSettingsViewModel`.
> Use IMessageBoxService in UpdateSettingsViewModel

- AnnoDesigner/PreferencesWindow.xaml
- AnnoDesigner/PreferencesWindow.xaml.cs
- AnnoDesigner/ViewModels/PreferencesViewModel.cs
> Add close button to PreferencesWindow

- AnnoDesigner/ViewModels/GeneralSettingsViewModel.cs
> Fix #267: Hide influence on selection not checked

- doc/Optimize_images.md
This PR adds a file to the docs with information on how to optimize the images.
> Add doc on how to optimize images

- AnnoDesigner/ViewModels/UpdateSettingsViewModel.cs
Not perfect, but better than nothing.
> Show update message box when update is available

- Tests/AnnoDesigner.Core.Tests/AnnoDesigner.Core.Tests.csproj
- Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
- Tests/PresetParser.Tests/PresetParser.Tests.csproj
This PR updates some dependencies, that were missing in the previous PR.
> Update missing dependencies

- AnnoDesigner.Core/Extensions/IEnumerableExtensions.cs
- AnnoDesigner/AnnoCanvas.xaml.cs
- AnnoDesigner/Helper/PolygonBoundaryFinderHelper.cs
- AnnoDesigner/Helper/RoadSearchHelper.cs
This PR is a small improvement to the performance by eliminating some pressure from the GC or just using a faster implementation.
All changes are based on a benchmark and data is based on the layout 
[Bigger_City_with_Palace_World_Fair_Centered.zip](https://github.com/AnnoDesigner/anno-designer/files/6624556/Bigger_City_with_Palace_World_Fair_Centered.zip).
Since all those methods are called very frequently these changes add up.
<details>
<summary>System used for benchmarks</summary>
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19042.1023 (20H2/October2020Update)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
[Host]     : .NET Framework 4.8 (4.8.4360.0), X64 RyuJIT
Job-WRGTJA : .NET Framework 4.8 (4.8.4360.0), X64 RyuJIT
Runtime=.NET Framework 4.8 …
```
> Small improvements to performance

- AnnoDesigner/Localization/Localization.cs
- AnnoDesigner/MainWindow.xaml
This PR fixes #201 and moves the different "Show" toggles into a new `View` menu.
> Fix #201: move toggles to separate menu

- AnnoDesigner/ViewModels/MainViewModel.cs
Also fixed undo operations not being cleared when loading layout from JSON string
> Merging roads is now undoable

- AnnoDesigner.Core/Presets/Models/BuildingInfo.cs
- AnnoDesigner.Core/Presets/Models/IBuildingInfo.cs
Make Presets.json can use Decimals on Influence Radius and Influence Distances, and the program read that normally
> Update Radius and Range for Decimals.

- AnnoDesigner/AnnoCanvas.xaml
- AnnoDesigner/StatisticsView.xaml
- AnnoDesigner/VersionView.xaml
- AnnoDesigner/VersionView.xaml.cs
- AnnoDesigner/ViewModels/MainViewModel.cs
> Added layout version to exported png file (#332)

- AnnoDesigner/AnnoCanvas.xaml.cs
This PR fixes the erroneous mouse handling after the latest merged performance improvements.
A quick profiling showed that the improvents are still relevant if there are no objects to be placed, the grid is not moved and the mouse is moved arround. This scenario should be by far the most common.
> Fix mouse handling after performance improvements

- AnnoDesigner/Models/LayoutObject.cs
- it will be done in the presets wherever it is needed
> Removed the hotfix to reduce influence radius of odd sized buildings #299

- AnnoDesigner.Core/Properties/AssemblyInfo.cs
- AnnoDesigner/Constants.cs
- AnnoDesigner/Properties/AssemblyInfo.cs
- PresetParser/Properties/AssemblyInfo.cs
This PR updates the version numbers for the release of 9.2.
The auto-update is **not** triggered.
> Update version numbers for release of 9.2

- AnnoDesigner.Core/AnnoDesigner.Core.csproj
- AnnoDesigner/AnnoDesigner.csproj
- AnnoDesigner/app.config
- ColorPresetsDesigner/App.config
- ColorPresetsDesigner/ColorPresetsDesigner.csproj
- FandomParser/FandomParser/FandomParser.csproj
- FandomParser/Tests/FandomParser.Tests/FandomParser.Tests.csproj
- FandomParser/Tests/InfoboxParser.Tests/InfoboxParser.Tests.csproj
- FandomTemplateExporter/FandomTemplateExporter/FandomTemplateExporter.csproj
- PresetParser/PresetParser.csproj
- PresetParser/app.config
- README.md
- Tests/AnnoDesigner.Core.Tests/AnnoDesigner.Core.Tests.csproj
- Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
- Tests/PresetParser.Tests/PresetParser.Tests.csproj
- build/build.cake
This PR fixes #378 by updating the `TargetFramework` to `net48`.
Also the ReadMe was updated and adjusted.
> Update TargetFramework to .NET 4.8

- ColorPresetsDesigner/ColorPresetsDesigner.csproj
- ColorPresetsDesigner/Properties/AssemblyInfo.cs
- ColorPresetsDesigner/Properties/Settings.Designer.cs
- ColorPresetsDesigner/ViewModels/MainWindowViewModel.cs
- ColorPresetsDesigner/ViewModels/PredefinedColorViewModel.cs
This PR removes already added identifiers from the list of available identifiers.
> ColorPresetsDesigner: Remove already added identifier from list of available identifiers

- ColorPresetsDesigner/App.xaml.cs
- ColorPresetsDesigner/MainWindow.xaml
- ColorPresetsDesigner/ViewModels/MainWindowViewModel.cs
This PR improves the `ColorPresetsDesigner`:
- identifiers for template are sorted
- added color is selected
- after deleting the first color is selected
- adjust designer view
- scrollbars actually work
> ColorPresetsDesigner: Some QOL improvements

- AnnoDesigner.Core/Properties/AssemblyInfo.cs
- AnnoDesigner/Constants.cs
- AnnoDesigner/Properties/AssemblyInfo.cs
- PresetParser/Properties/AssemblyInfo.cs
This PR updates the version numbers to `9.4.0.0` for the new release.
> Update version numbers

- PresetParser/Program.cs
Fixed Replaced GUIDs for the Tool Anno1800SavegameVisualizer
*No New Update is needed for the Presets.json file*
> Update PresetParser for Anno1800 Savegame Visualizer
