AnnoDesigner/MainWindow.xaml
AnnoDesigner/MainWindow.xaml.cs

I added some DoubleUpDown/IntegerUpDown controls from the WPF Toolkit.
this adds an aditional way of entering values and also adds some validition to the input fileds.
Before you could enter "foo" for width, heigth or radius and there was a messagebox with "incorrect building config". Now there will be entered the default value when loosing focus.

use numeric up down controls

---

AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/App.xaml.cs
AnnoDesigner/MainWindow.xaml.cs
AnnoDesigner/app.config
PresetParser/PresetParser.csproj
PresetParser/app.config

Since .NET Framework 4.7.2 is available via Windows Update this should not trigger any installation on customer side.
Doing so enables the app to take advantage of some fixes/enhancements on High DPI displays.
Targeting .NET 4.8 would require Visual Studio 2019 on developer side. I think targeting .NET 4.7.2 should still allow Visual Studio back to 2015. Not sure about that, but definitely Visual studio 2017.
And for VS >=2017 there is a free Community edition.
[Can I use Visual Studio 2015 to target .net framework 4.7](https://stackoverflow.com/a/43420229)
[.NET Framework 4.7.2 is available on Windows Update, WSUS and MU Catalog](https://devblogs.microsoft.com/dotnet/net-framework-4-7-2-is-available-on-windows-update-wsus-and-mu-catalog/)
[Lifecycle FAQ—.NET …

retarget to use .NET Framework 4.7.2

---

AnnoDesigner/Localization.cs
AnnoDesigner/MainWindow.xaml.cs

fixes #33, localizes 3 other symbols in the help menu that were missed previously

Localize Items on clipboard

---

AnnoDesigner/Localization.cs
AnnoDesigner/MainWindow.xaml
AnnoDesigner/TreeViewExtensions.cs
AnnoDesigner/TreeViewSearch.cs

* Fix the for the null reference exception when switching languages (bug in ExpandAncestors).
* Localised the "Search" string
* Fixed some inconsistencies with the search results as they were displaying branches that matched the search token, which resulted in empty branches in the result

Presets search null reference exception fix

---

AnnoDesigner/MainWindow.xaml.cs

This caused an issue in 8.2 for a user, where they had closed the window while it was minimised. 
This meant the RenderSize.Height property was set to 0, so when `OnRender` ran (it runs once when the window starts minimised), the stats panel failed to draw, as `RenderSize.Height` was 0, which was an invalid value for the `MaxTextHeight` property of `FormattedText`.
This isn't an issue in the new release, but it should be safer to add this. It also doesn't make any sense for the window to start minimised anyway.

if window is minimised when closing, set to WindowState.Normal

---

AnnoDesigner/MainWindow.xaml

Prevents the tree view from auto resizing when the user is searching. It ensures a scrollbar appears instead. The user can still resize the grid to epxand the width of the treeview.

prevent tree view auto-resize when searching

---

AnnoDesigner/Presets/BuildingInfo.cs
AnnoDesigner/TreeLocalization.cs

If translation(s) is not found in ether Treeview translation or in the preset file, the tree or object will be translated in English

Made Failsafe for missing TreeView Translation and Preset Translation

---

AnnoDesigner/App.xaml.cs
AnnoDesigner/Properties/Settings.Designer.cs
AnnoDesigner/Properties/Settings.settings
AnnoDesigner/app.config

This PR checks if the settings need an upgrade and migrate the settings from the old version.
The user doesn't need to select the language on every app update. 🎉 (at least that bothered me)

migrate settings on app update

---

AnnoDesigner/MainWindow.xaml.cs
AnnoDesigner/PresetsLoader/IconLoader.cs

When I created a layout with version 8.2 and presets 3.1.1 and then tried to load it in the current development version some icons were missing.
For example in my test the layout contained an icon "A7_**w**arehouse" and the app just knows of "A7_**W**arehouse". So just a simple mismatch in case.
The reason is (in `AnnoCanvas.RenderObject`):
```csharp
if (iconName != null && Icons.ContainsKey(iconName))
```
`Icons`is a `Dictionary<string, IconImage>` and by default the `ContainsKey` method is caseSensitive.
So to fix this the dictionary is created with a different default comparer.

fix for missing icons when loading old layouts (created with old presets)

---

AnnoDesigner/Presets/BuildingPresets.cs

Sort the Objects on Translation Names instead of Group name where Group is `null`
before : 
after :

Preset View Sorting

---

AnnoDesigner/viewmodel/StatisticsViewModel.cs

This PR fixes "flicker" (don't know how to name it) in the statistics view.
Actually there was no explicit sort of the buildings, but now there is.
See images for explanation:
- before
- after

fix flicker in statistics view

---

AnnoDesigner.Core/Presets/Helper/ColorPresetsHelper.cs

Fix wrong color when there is a predefined color without identifiers before a color with identifiers.
Reported by @StingMcRay via discord:

fix predefined color

---

AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/InputWindow.xaml
AnnoDesigner/InputWindow.xaml.cs
AnnoDesigner/Localization.cs
AnnoDesigner/MainWindow.xaml
AnnoDesigner/MainWindow.xaml.cs

This PR adds the possibility to save the current layout as JSON to the clipboard and also to load a layout from a pasted JSON string.
This feature came up on discord to ad layout "files" to the provided layouts in the wiki.

Add import/export from/to JSON string

---

AnnoDesigner/MainWindow.xaml
AnnoDesigner/MainWindow.xaml.cs

This PR fixes the issue, that the event to repopulate the tree is raised multiple times when the language is changed.

raise only one event when language is changed

---

AnnoDesigner/AnnoCanvas.xaml.cs
Tests/AnnoDesigner.Core.Tests/LayoutLoaderTests.cs

This PR fixes an issue when the user selected a color with transparency and use the "Place Building" button.
There are also tests to ensure load/save of layouts with transparent colors.

allow transparency on "Place Building"

---

AnnoDesigner.Core/AnnoDesigner.Core.csproj
AnnoDesigner.Core/Presets/Loader/BuildingPresetsLoader.cs
AnnoDesigner.Core/Presets/Loader/ColorPresetsLoader.cs
AnnoDesigner.Core/Presets/Loader/IconLoader.cs
AnnoDesigner.Core/Presets/Loader/IconMappingPresetsLoader.cs
AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/App.xaml.cs
AnnoDesigner/Commons.cs
AnnoDesigner/Localization/TreeLocalization.cs
AnnoDesigner/MainWindow.xaml.cs
AnnoDesigner/UpdateHelper.cs
AnnoDesigner/app.config
AnnoDesigner/viewmodel/BuildingSettingsViewModel.cs
AnnoDesigner/viewmodel/PresetsTreeViewModel.cs
ColorPresetsDesigner/App.config
ColorPresetsDesigner/ColorPresetsDesigner.csproj
FandomParser/FandomParser/App.config
FandomParser/FandomParser/FandomParser.csproj
FandomParser/Tests/InfoboxParser.Tests/InfoboxParser.Tests.csproj
FandomTemplateExporter/FandomTemplateExporter/App.config
FandomTemplateExporter/FandomTemplateExporter/FandomTemplateExporter.csproj
PresetParser/PresetParser.csproj
Tests/AnnoDesigner.Core.Tests/AnnoDesigner.Core.Tests.csproj
Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
Tests/PresetParser.Tests/PresetParser.Tests.csproj
build/build.cake

This PR should fix #122.
With this PR there are proper formatted log files in a common location (directory "logs" app directory).
The added logging framework is [NLog](https://nlog-project.org/).
The format of those log files can be adjusted (via app.config) and currently the log files of the last 7 days will be kept in an archive as zip-files.
The current format is:
`Timestamp||Level||Logger||Message`
Example:
`2019-09-26 14:14:51||INFO ||AnnoDesigner.App||program version: 8.2.0.0`
In case of an error there will be plenty of information in the log (e.g. StackTrace, ExceptionData, InnerExceptions).
Example (german runtime):
> 2019-09-26 13:22:10||ERROR||AnnoDesigner.App||Application.Current.DispatcherUnhandledException
> System.Exception: Testexception that is thrown on purpose. ---> …

fix #122 (add proper solution for logging )

---

LICENSE

This adjusts the structure of the license file so GitHub can recognize it automatically.
I just merged the "Copyright ..." lines so it is recognized as the ususal template used by GitHub.
current state:
expected state:

adjust license structure to autorecognize it

---

AnnoDesigner/AnnoCanvas.xaml.cs

This PR changes the order of drawing the selection.
New behaviour is on the left side:

draw selection before influence

---

AnnoDesigner.Core/Models/IconImage.cs

This PR greatly improves the performance when the icons are shown.
> This is one small change for me, one giant leap for performance.
It is hard to tell the difference with numbers, because there are so many more `OnRender` calls possible now. If you move your mouse over a large layout you definitely feel/see the improvement.

improve performance of drawing the icons

---

AnnoDesigner/About.xaml
AnnoDesigner/AnnoDesigner.csproj

Icon was included as <Content> rather than <Resource>, meaning it looked fine in debug or release modes when run through the IDE, but failed when the build script was ran, as the build script has a specific list of whitelisted files that it copies to the output directory.
This PR fixes that issue.
Also brings up some questions about cleaning up what files we output to the Release directory so we can just zip the entire directory in future - maybe something we could look at in issue #187.

Fix the issue causing the About page icon to disappear

---

Directory.Build.props

This PR adds a `Directory.Build.props` so any project uses the latest version of C# available.
See [MSDN](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) for reference.

always use latetst version of C#

---

AnnoDesigner/ViewModels/StatisticsViewModel.cs

This PR fixes some issues I encountered with the statistics view when it is updated async.
Sometimes a collection was modified or an element in the collection was null.
Most of the time the error occured when closing the app.

fixed issues with async update of statistics view

---

AnnoDesigner/AnnoCanvas.xaml.cs

This PR fixes a behaviour which annoyed me.
You can drag the whole layout by pressing both mouse buttons (left and right). But if you have a building "on your cursor" it was always placed, when the right button was pressed before the left button.
This is fixed now.
If you like the current behaviour, just close this PR.
- place some buildings
- select a building so that it "sticks to the cursor"
- press right mouse button (no release)
- press left mouse button (no release)
- move mouse
-> building is placed
- place some buildings
- select a building so that it "sticks to the cursor"
- press right mouse button (no release)
- press left mouse button (no release)
- move mouse
-> building is **not** placed

DragAll: Do not place building if right click was before left click

---

AnnoDesigner/MainWindow.xaml

This PR adds the corresponding images to the menu `Language` menu item.

Add image to language menu items

---

AnnoDesigner/Localization/LocalizeBinding.cs

Makes a data binding which translates a key from another binding based on currently selected language.
All following examples are equivalent:
`<TextBlock Text={l:DynamicLocalize PathToTraslationKey}/>`
`<TextBlock Text={l:DynamicLocalize KeyPath=PathToTraslationKey}/>`
```
<TextBlock>
<TextBlock.Text>
<l:DynamicLocalize>
<Binding Path="PathToTraslationKey"/>
</l:DynamicLocalize>
</TextBlock.Text>
</TextBlock>
```
DynamicLocalize is prepared MultiBinding, so it you need something that it doesn't support (like specific Source, Converter, ...), use third example.

Implemented translating dynamic key

---

AnnoDesigner.Core/Extensions/MessageBoxServiceExtensions.cs
AnnoDesigner.Core/Services/IMessageBoxService.cs
AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/App.xaml.cs
AnnoDesigner/Commons.cs
AnnoDesigner/PreferencesWindow.xaml.cs
AnnoDesigner/Services/MessageBoxService.cs
AnnoDesigner/UpdateHelper.cs
AnnoDesigner/ViewModels/BuildingSettingsViewModel.cs
AnnoDesigner/ViewModels/MainViewModel.cs
AnnoDesigner/ViewModels/ManageKeybindingsViewModel.cs
AnnoDesigner/ViewModels/PreferencesViewModel.cs
Tests/AnnoDesigner.Tests/BuildingSettingsViewModelTests.cs
Tests/AnnoDesigner.Tests/MainViewModelTests.cs

This PR adds a service which abstracts the use of `MessageBox`es.
It is considered as a first step to localize `MessageBox`es (#71).

Add service to abstract MessageBoxes

---

AnnoDesigner.Core/Helper/SerializationHelper.cs
AnnoDesigner.Core/Models/IAppSettings.cs
AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/Models/AppSettings.cs
AnnoDesigner/Properties/Settings.Designer.cs
AnnoDesigner/Properties/Settings.settings
AnnoDesigner/ViewModels/MainViewModel.cs
AnnoDesigner/app.config

This PR adds the functionality to load the colors for grid lines and object borders from the settings.
It is a step towards fixing the issue #211.
A UI for changing the color will be added with PR #238.

Add support for loading colors (grid lines; object border lines) from settings

---

AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/LicensesWindow.xaml
AnnoDesigner/Models/LicenseInfo.cs
AnnoDesigner/ViewModels/LicensesViewModel.cs

This PR fixes #236.
Also the Toolkit was updated to latest usable version (3.8.2) to comply with the license.
The Toggle to show assets is only shown if there are assets present.

Add WPFToolkit to Licenses window (fix #236)

---

AnnoDesigner/ViewModels/GeneralSettingsViewModel.cs
Tests/AnnoDesigner.Tests/MainViewModelTests.cs
Tests/AnnoDesigner.Tests/UserDefinedColorToDisplayNameConverterTests.cs

This PR fixes the failling tests after PR #238 was merged.
**Note:**
Because the `Localization` class is not abstracted there still could be failling tests inside Visual Studio.
But only if `Run Tests In Parallel` is active.
I was not able to reproduce a failling test when using the build script.

Fix failling tests after PR #238

---

AnnoDesigner/App.xaml.cs
AnnoDesigner/Commons.cs
AnnoDesigner/Models/ICommons.cs
AnnoDesigner/ViewModels/MainViewModel.cs
AnnoDesigner/ViewModels/UpdateSettingsViewModel.cs
Tests/AnnoDesigner.Tests/MainViewModelTests.cs

This PR moves the `IUpdateHelper` out of `ICommons`.
The primary case is to help PR #243, but I wanted to make it a separate change/PR.

Remove `IUpdateHelper` from `ICommons`

---

AnnoDesigner/Constants.cs
AnnoDesigner/Localization/Localization.cs
AnnoDesigner/PreferencesPages/GeneralSettingsPage.xaml
AnnoDesigner/ViewModels/GeneralSettingsViewModel.cs

This PR fixes #257 and adds a "Default" button to restore the zoom sensitivity to the default value (50).

Fix #257: Add "Default" button to zoom sensitivity

---

AnnoDesigner/Localization/TreeLocalization.cs

Add the missing translations of the Tree Menu : Anno 1800 > Investors > Palace Buildings

Fix missing tree transelatons of Palace Buildings (issue #264)

---

AnnoDesigner/ViewModels/GeneralSettingsViewModel.cs

Fixes #251.
The sources for the combo boxes were being cleared when the selected language was changed so they could be localised. This updated the selected values to be `null`, which fired the property changed events.

Fix 251 - NullReferenceException when changing language and Preferences window is open

---

.editorconfig
AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/App.xaml.cs
AnnoDesigner/MainWindow.xaml.cs
AnnoDesigner/app.manifest

This PR opts-in to per-monitor DPI awareness.
https://github.com/Microsoft/WPF-Samples/tree/master/PerMonitorDPI
Its not perfect on my machine, but its better than the old blurry text. When I move the window from my 4k monitor to a 1080p monitor, the window title bar extends to double height, and context menu text is much larger:
Updated:
Original:
The blurry text does not show up on the images, but the overall result despite the double height title bar is much more bearable.
Additionally, this also tweaks the editor config to remove the "Object initialisation can be simplified" message (as I'm fine with either method, and it saves no lines of code nor makes anything clearer), and tweaks the App.xaml.cs file (just using pattern matching where suggested and simplifying the using …

Opt in to per-monitor DPI awareness

---

AnnoDesigner/Commons.cs

Prevents an exception when starting the application.

Only include supported languages in LanguageCodeMap

---

Tests/AnnoDesigner.Tests/MainViewModelTests.cs

Fixes a nullref exception that caused some of the unit tests to fail. The new `QuadTree` used for AnnoCanvas does not have a default constructor, so needs to be set up explicitly for mocking from.

Fix failing tests - setup up PlacedObjects property explicitly

---

AnnoDesigner/ViewModels/GeneralSettingsViewModel.cs

A few checkboxes were not being repopulated when the viewmodel was being created.

Load missing settings on General Settings page

---

AnnoDesigner.Core/DataStructures/QuadTree.cs
AnnoDesigner/AnnoCanvas.xaml.cs

Quick hotfix - bounds within the QuadTree were stale after calling normalize. This PR resolves that issue, and will fix #285.

Fix stale quadtree bounds after normalize

---

AnnoDesigner/AnnoCanvas.xaml.cs

Fix rounding issue when placing objects, fix a crash to desktop

---

AnnoDesigner/Models/LayoutObject.cs
Tests/AnnoDesigner.Tests/LayoutObjectTests.cs

Change Circle Range Behavior for Odd number buildings (3x3/3x5 etc) to get rid of the half grid drawing that is not correct vs game circle ranges

Fixing issue #299

---

AnnoDesigner/ViewModels/UpdateSettingsViewModel.cs

This PR fixes an issue that prevents the download of new presets at application startup.
The download/update via the `Preferences` window doesn't have this issue.

Fix no auto download of presets at startup

---

AnnoDesigner.Core/Properties/AssemblyInfo.cs
build/build.cake
build/tools/packages.config

This PR adjusts the build script to the new version format (`Version` vs `double`). Also the dependencies were updated.
The missing adjustment of `AssemblyInfo` inside `AnnoDesigner.Core` was also fixed.

Adjust build script to new version format

---

AnnoDesigner/MainWindow.xaml
AnnoDesigner/ViewModels/BuildingSettingsViewModel.cs
AnnoDesigner/ViewModels/MainViewModel.cs
AnnoDesigner/ViewModels/StatisticsViewModel.cs

Made hidden TextBox named BuildingRealName for the following:
User can change the Building Names (for objects and statisitcBuilding.Name), and when they do, Identifier and Template Names will be changed into this name
"Building name not fount" will only be there if there is something really wrong.
Fix wrongly named Residences of Embesa and Arctic Anno 1800

Change "Unknown Object" Behavior.

---

AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/Helper/PolygonBoundaryFinderHelper.cs
AnnoDesigner/MainWindow.xaml
Tests/AnnoDesigner.Tests/PolygonBoundaryFinderHelperTests.cs

Implemented search for holes in the PolygonBoundaryFinderHelper

---

AnnoDesigner/ViewModels/PresetsTreeViewModel.cs

This PR tweaks the search to check the header of the nodes when searching.
Before if there was no child matching the search the node was hidden.
After if there is no child matching the search the node is visible. To avoid cluttering the tree the node is not expanded.
If there is a demand to not check the header it is possible to add a new option to the preferences window.

Show tree node if header matches search text

---

AnnoDesigner/ViewModels/PresetsTreeViewModel.cs
Tests/AnnoDesigner.Tests/PresetsTreeViewModelTests.cs

This PR adds localization for unknown games. A unknown game is e.g. the road presets.

Add localization for "- Road Presets" to presets tree

---

AnnoDesigner.Core/DataStructures/QuadTree.cs

This PR replaces LINQ in the hot path `QuadTree.GetItemsIntersecting(List<T> items, Rect bounds)` with a simple loop to reduce allocations.
Also a typo in `QuadTree.Quadrant(Rect extent)` is fixed.

Replace LINQ with simple loop in hot path

---

AnnoDesigner.Core/Properties/AssemblyInfo.cs
AnnoDesigner/Constants.cs
AnnoDesigner/Properties/AssemblyInfo.cs
PresetParser/Properties/AssemblyInfo.cs

This PR updates all relevant version numbers for release 9.1 (without triggering auto-uupdate and updating the main ReadMe).

Update version numbers for release of 9.1

---

AnnoDesigner/ViewModels/MainViewModel.cs

to avoid problems with QuadTree extent when normalizing before the export

Copied QuadTree extent during export to png (#341)

---

AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/Models/LayoutObject.cs

This PR adds some minor performance improvements in `OnRender`.
The most improvement is possibly on weaker systems with large layouts. Profiling shows some improvements, but don't expect wonders.
Basically it removes the need to create a new `List<LayoutObject>` on every call of `OnRender` if there are no changes in the `PlacedObjects` or the viewport.
<details>
<summary>Click to expand!</summary>  
</details>
<details>
<summary>Click to expand!</summary>  
</details>

minor performance improvement

---

AnnoDesigner/AnnoCanvas.xaml.cs

This PR fixes an issue with the rendering when deleting an object via keyboard shortcut.
To reproduce the issue:
- place some buildings by drag-drawing them
- select either single or multiple buildings
- delete them (via keyboard)

Fix rendering when deleting object

---

AnnoDesigner.Core/AnnoDesigner.Core.csproj
PresetParser/PresetParser.csproj
Tests/AnnoDesigner.Core.Tests/AnnoDesigner.Core.Tests.csproj
Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
Tests/PresetParser.Tests/PresetParser.Tests.csproj

This PR removes some unnecessary entries inside the `.csproj` files.
Most of them are left overs from the conversion to the new SDK style project files.

🧹 Remove unnecessary entries in .csproj

---

Tests/PresetParser.Tests/ExtraPresetsTests.cs
build/build.cake

This PR updates the build script to copy the missing `Microsoft.Bcl.HashCode.dll` to the output directory.
Also some failing tests from the `PresetParser` are fixed.

Update build script

---

AnnoDesigner/Models/IUpdateHelper.cs
AnnoDesigner/Models/ReleaseType.cs
AnnoDesigner/PreferencesPages/UpdateSettingsPage.xaml
AnnoDesigner/UpdateHelper.cs
AnnoDesigner/ViewModels/UpdateSettingsViewModel.cs

This PR kind of fixes the `UpdateHelper` to also check for pre-releases of the app, if the corresponding setting is checked.
The check for pre-releases of presets was already present and working.
Also the new version is displayed inside the preferences window.

Auto update supports prerelease of app

---

AnnoDesigner.Core/AnnoDesigner.Core.csproj
AnnoDesigner/AnnoDesigner.csproj
AnnoDesigner/app.config
ColorPresetsDesigner/App.config
ColorPresetsDesigner/ColorPresetsDesigner.csproj
Directory.Build.targets
FandomParser/FandomParser.Core/FandomParser.Core.csproj
FandomParser/FandomParser/App.config
FandomParser/FandomParser/FandomParser.csproj
FandomParser/InfoboxParser/InfoboxParser.csproj
FandomTemplateExporter/FandomTemplateExporter/App.config
FandomTemplateExporter/FandomTemplateExporter/FandomTemplateExporter.csproj
PresetParser/PresetParser.csproj
Tests/AnnoDesigner.Core.Tests/AnnoDesigner.Core.Tests.csproj
Tests/AnnoDesigner.Tests/AnnoDesigner.Tests.csproj
Tests/PresetParser.Tests/PresetParser.Tests.csproj

This PR fixes #387.
Also the dependencies were updated and the version numbers of those dependencies is now at a central location (`Directory.Build.targets`).

Fix wrong location of log file

---

AnnoDesigner.Core/CoreConstants.cs
AnnoDesigner.Core/Layout/Models/LayoutFile.cs
AnnoDesigner.Core/Models/IClipboard.cs
AnnoDesigner.Core/Models/WindowsClipboard.cs
AnnoDesigner.Core/Services/ClipboardService.cs
AnnoDesigner.Core/Services/IClipboardService.cs
AnnoDesigner/AnnoCanvas.xaml.cs
AnnoDesigner/ClipboardManager.cs
AnnoDesigner/Constants.cs
AnnoDesigner/MainWindow.xaml
AnnoDesigner/Models/IAnnoCanvas.cs
AnnoDesigner/ViewModels/MainViewModel.cs
Tests/AnnoDesigner.Core.Tests/ClipboardServiceTests.cs
Tests/AnnoDesigner.Core.Tests/Mocks/MockedClipboard.cs
Tests/AnnoDesigner.Tests/MainViewModelTests.cs

Implemented pasting from Windows clipboard. Supported sources:
- .ad file
- .ad file's string content
- old copy/paste functionality

Use Windows clipboard instead of custom logic for clipboard

---

AnnoDesigner.Core/Models/IAppSettings.cs
AnnoDesigner/Localization/Localization.cs
AnnoDesigner/MainWindow.xaml
AnnoDesigner/Models/AppSettings.cs
AnnoDesigner/Properties/Settings.Designer.cs
AnnoDesigner/Properties/Settings.settings
AnnoDesigner/ViewModels/MainViewModel.cs
AnnoDesigner/app.config
Tests/AnnoDesigner.Tests/MainViewModelTests.cs

This PR fixes #411.
Because the option is also available via command line it is made available via the menu.

Add option to hide version on exported image

---

AnnoDesigner/App.xaml.cs

This PR fixes #414.
The language selection is not shown when the app is first used via command line to export images and the language is set to `English`.
The dialog is still shown on first use if started normally or via command line using the `open` command.

Prevent language selection when used via command line

---

AnnoDesigner/AnnoCanvas.xaml.cs

- same levels of different tiers increase panorama instead of decreasing it
- other rules are the same

Fixed outdated panorama calculation #437
